---

- name: Disable NTP service
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    state: stopped
    enabled: false
    daemon_reload: true
  failed_when: false  # services may not exist
  tags:
    - gps
    - conf

- name: Disable PTP services (some entries will fail)
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
  with_items:
    - phc2sys.service # TODO: these fail in recent ubuntu nightlies, linuxptp switched to servive-templates, keep old style for now
    - ptp4l.service
    - phc2sys@eth0.service
    - ptp4l@eth0.service
  when: '"ptp_clients" not in group_names and "ptp_servers" not in group_names'
  failed_when: false  # services may not exist
  tags:
    - gps
    - conf

- name: Enable GPS services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  with_items:
    - chrony.service
    - gpsd.socket
  tags:
    - gps
    - conf
