---
# user can control rule by altering these vars from outside
do_delete_recordings: false
do_remove_software: true
do_zero_free_space: false


#### software to remove ####

# potentially dangerous / improve security:
non_essential_packages_a: ['dnsmasq', 'dnsmasq-*', 'nginx', 'nginx-*']
# old kernel data # TODO: kernel / header that comes with image are somehow not in apt -> dpkgs
non_essential_packages_b: ['linux-image-4.14.*', 'linux-image-5.4.*', 'linux-image-5.10.*', 'linux-image-5.15.*']
non_essential_packages_c: ['linux-headers-4.14.*', 'linux-headers-5.4.*', 'linux-headers-5.10.*', 'linux-headers-5.15.*']
# todo: soon add linux-*-4.19.*
# not needed drivers / packages
non_essential_packages_d: ['alsa-utils', 'wireless-*', 'wpasupplicant', 'ofono', 'bluez', 'bluetooth', 'rfkill']
non_essential_packages_e: ['seeed-modules-*', 'rtl8*', 'can-utils', 'libasound*']
non_essential_packages_f: ['ti-sgx-*', 'eject', 'iw', 'initramfs*']
non_essential_packages_g: ['vim-runtime', 'humanity-icon-theme', 'python3-sympy']
# - add: libjpeg*,? part of sheep-install
# NOTE: 'libx11*' part of python3-h5py
