---

# user can control rule by altering these vars from outside
update_kernel: false
update_bootloader: false
delete_unused_files: true

# rule config
default_kernel_branch: lts-4_19
timezone: Europe/Berlin
