---
- name: Configure PTP for server-mode (time-coordinator)
  ansible.builtin.lineinfile:
    dest: "/etc/linuxptp/ptp4l.conf"
    regexp: "slaveOnly.*$"
    line: "slaveOnly  0"
    state: present
  tags:
    - ptp
    - conf

- name: Disable NTP service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: false
    daemon_reload: true
  failed_when: false  # services may not exist
  tags:
    - ptp
    - conf

- name: Disable GPS services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
  with_items:
    - gpsd.socket
    - chrony.service
  when: '"gps_clients" not in group_names'
  failed_when: false  # services may not exist
  tags:
    - ptp
    - conf

- name: Enable PTP services (some entries will fail)
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  with_items:
    - phc2sys.service # TODO: these fail in recent ubuntu nightlies, linuxptp switched to servive-templates, keep old style for now
    - ptp4l.service
    - phc2sys@eth0.service
    - ptp4l@eth0.service
  failed_when: false  # services may not exist
  tags:
    - ptp
    - conf
