---
- name: Install Shepherd-Software - Role-based
  hosts: sheep
  become: true

  pre_tasks:

    - name: Get time and date from ansible controller
      ansible.builtin.command: 'date -u +"%Y-%m-%dT%H:%M:%SZ"'
      delegate_to: localhost
      changed_when: false
      register: local_time
      become: false
    - name: Set correct time
      ansible.builtin.command: "date -s {{ local_time.stdout }}"
      changed_when: true

    - name: Update kernel, bootloader, software & cleanup afterwards
      ansible.builtin.include_role:
        name: maintained
      vars:
        update_kernel: true
        update_bootloader: true
        delete_unused_files: true

- name: Main-Software for Shepherd
  hosts: sheep
  become: true
  roles:
    - sheep

- name: Role - PTP-Client
  hosts: ptp_clients
  become: true
  roles:
    - ptp_client

- name: Role - NTP-Client
  hosts: ntp_clients
  become: true
  roles:
    - ntp_client

- name: Role - GPS-Client
  hosts: gps_clients
  become: true
  roles:
    - gps_client
# TODO: how to avoid allowing gps & ptp & ntp client? trouble ahead
#       -> could switch to components and argument_specs
#       https://steampunk.si/blog/ansible-role-argument-specification/

- name: Role - PTP-Server
  hosts: ptp_servers
  become: true
  roles:
    - ptp_server

- name: Role - Secured Testbed
  hosts: secured
  become: true
  roles:
    - secure_testbed

- name: Install Shepherd-Software - Role-based
  hosts: sheep
  become: true

  # post_tasks:
  tasks:

    - name: Cleanup after software
      ansible.builtin.include_role:
        name: maintained
      vars:
        update_kernel: false
        update_bootloader: false
        delete_unused_files: true
