---
- name: Deposit your machines' certificates (host) to nodes for future password-less ssh-logins
  hosts: all
  become: true
  gather_facts: false

  vars_prompt:
    - name: current_password
      prompt: "Provide current target-password"
      private: true

  tasks:

    - name: Set provided PW for current playbook
      ansible.builtin.set_fact:
        # special internal variables:
        ansible_password: "{{ current_password }}"
        ansible_become_password: "{{ current_password }}"

    - name: Enable and setup password-less ssh-login via authorized key from local file (prereq is run of ssh-keygen)
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Restart device
      ansible.builtin.reboot:
