---
- name: Configure PTP for master mode
  lineinfile:
    dest: "/etc/linuxptp/ptp4l.conf"
    regexp: "slaveOnly.*$"
    line: "slaveOnly  0"
    state: present
  tags:
    - ptp
    - conf

- name: Disable NTP service
  systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: yes  # services may not exist
  tags:
    - ptp
    - conf

- name: Disable GPS services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  with_items:
    - gpsd.socket
    - chrony.service
  when: '"gps_clients" not in group_names'
  ignore_errors: yes  # services may not exist
  tags:
    - ptp
    - conf

- name: Enable PTP services (some entries will fail)
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items:
    - phc2sys.service # TODO: these fail in recent ubuntu nightlies, linuxptp switched to servive-templates, keep old style for now
    - ptp4l.service
    - phc2sys@eth0.service
    - ptp4l@eth0.service
  ignore_errors: yes  # services may not exist
  tags:
    - ptp
    - conf
