name: Build Pru CGT

on:
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
# TODO: compilation fails with: exec() error spawning acpiapru: No such file or directory

  pru-tests:
    runs-on: ubuntu-latest
    env:
      pru_cgt_installer: "ti_cgt_pru_2.3.3_linux_installer_x86.bin"
      pru_cgt_link_pre: "https://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/2.3.3/"
      pru_support_package: "pru-software-support-package-5.9.0"
      pru_support_link_pre: "https://git.ti.com/cgit/cgit.cgi/pru-software-support-package/pru-software-support-package.git/snapshot/"
      PRU_CGT: "/usr/share/ti/ti-cgt-pru_2.3.3"
      PRU_CGT_SUPPORT: "/usr/share/ti/pru-software-support-package-5.9.0"

    steps:

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install 32bit dependencies ğŸ”§
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386

      - name: Install APT dependencies ğŸ”§
        run: sudo apt install build-essential

      - name: prepare directory
        run: mkdir -p ${{ env.PRU_CGT }}/bin

      - name: Install CGT dependency ğŸ”§
        run: |
          sudo wget -q --tries 3 ${{ env.pru_cgt_link_pre }}${{ env.pru_cgt_installer }}
          sudo chmod a+x ./${{ env.pru_cgt_installer }}
          sudo ./${{ env.pru_cgt_installer }}
        working-directory: /usr/share/ti

      - name: Install PSSP dependency ğŸ”§
        run: git clone --branch v5.9.0 https://git.ti.com/cgit/cgit.cgi/pru-software-support-package/pru-software-support-package.git
        working-directory: /usr/share/ti

      - name: Prepare using CGT ğŸ²
        run: |
          file ${{ env.PRU_CGT }}/bin/clpru
          sudo ln -s ${{ env.PRU_CGT }}/bin/clpru /usr/bin/clpru
          sudo ln -s ${{ env.PRU_CGT }}/bin/lnkpru /usr/bin/lnkpru

#      - name: Build PRU0 ğŸ§±
#        run: |
#          export PATH=$PATH:$PRU_CGT
#          sudo make
#        working-directory: "software/firmware/pru0-shepherd-fw/"

#      - name: Build PRU1 ğŸ§±
#        run: |
#          export PATH=$PATH:$PRU_CGT
#          sudo make
#        working-directory: "software/firmware/pru1-shepherd-fw/"
