name: Generate Docs
# for Github-Pages

on:
  push:
    branches: [ "main" ]
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-quality-control:
    uses: ./.github/workflows/quality_control.yml
  build-pages:
    runs-on: ubuntu-latest
    needs:
      - run-quality-control
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          submodules: true  # for grabbing readme-files

      - name: Build and Push Pages ğŸ§±
        uses: sphinx-notes/pages@v3
        with:
          checkout: false
          pyproject_extras: ""
          # currently needed because action begins to analyze root pyproject.toml
