name: Test Sheep

on:
  workflow_call:

jobs:
  unittest-sheep:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.13", "3.12", "3.11", "3.10" ]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies ğŸ”§
        run: |
          sudo apt update
          sudo apt install python3-msgpack
          python3 -m pip install --upgrade pip msgpack

      - name: Install the shepherd py-package ğŸ‘
        run: "pip3 install .[test]"
        working-directory: "./software/python-package"
      - name: Test the shepherd py-package (limited test-range) ğŸ
        run: "pytest"
        working-directory: "./software/python-package"
        # needs sudo because it installs packages
