name: Test for Quality Control

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]  # TODO: reactivate "3.12", failing ATM (2023-11-06)
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies ğŸ”§
        run: |
          sudo apt update
          sudo apt install python3-msgpack
          sudo apt install cppcheck
          python3 -m pip install --upgrade pip msgpack
          pip3 install ansible -U
          ansible-galaxy collection install ansible.posix
          ansible-galaxy collection install community.general
        # NOTE: install-process fails without msgpack pre-installed
        # NOTE: cppcheck is needed for pre-commit
        # NOTE: ansible + collections might be needed for linter

      - name: Run Pre-Commit Tests ğŸ§ª
        uses: pre-commit/action@v3.0.0

      - name: Install the shepherd py-package ğŸ‘
        run: "sudo pip3 install ./[test]"
        working-directory: "./software/python-package"
      - name: Test the shepherd py-package (limited test-range) ğŸ
        run: "sudo pytest"
        working-directory: "./software/python-package"
        # needs sudo because it installs packages

      - name: Install the shepherd-herd py-package ğ“‹¿ ğ“€
        run: "sudo pip3 install ./"
        working-directory: "./software/shepherd-herd"
